Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt-get -y update
    sudo apt-get install -y python3 python3-pip python3-dev postgresql-server-dev-all python3-django 
    pip3 install psycopg2
    SHELL
end
